name: Publish NuGet packages
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore -p:Version=${{ github.event.release.tag_name }} -p:ContinuousIntegrationBuild=true
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack
      run: dotnet pack -c Release --no-build -p:PackageVersion=${{ github.event.release.tag_name }} -o "bin/Release" --include-symbols --include-source
    - name: Push NuGet packages
      run: dotnet nuget push "bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
